apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-pubsub
  labels:
    app: springboot-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-pubsub
  template:
    metadata:
      name: springboot-pubsub
      labels:
        app: springboot-pubsub
    spec:
      containers:
        - name: springboot-pubsub
          image: sravangcpdocker/jdk-pubsub:1.0
          env:
            - name: "TOPIC"
              value: PubSubDemo
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secret/cloud.google.com/service-account.json"
          volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
            - name: "certs"
              mountPath: "/etc/ssl/certs"
      volumes:
        - name: "service-account"
          secret:
            secretName: "my-app-sa-key"
        - name: "certs"
          hostPath:
            path: "/etc/ssl/certs"
